schema_version: 1

context:
  # Note: we use this variable everywhere except in outputs names as jinja variables in output names are not supported
  # by migrators, see https://github.com/conda-forge/librobometry-feedstock/pull/20#issuecomment-2041618340
  cxx_name: libgz-sim-yarp-plugins
  plugin_name: gz-sim-yarp-plugins
  name: gz-sim-yarp-plugins-split
  version: "0.5.3"
  build_number: 3

recipe:
  name: ${{ name }}
  version: ${{ version }}


source:
  url: https://github.com/robotology/gz-sim-yarp-plugins/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 23e25d7a425691ab5dfae25deb235ebe84bd540a5cac4f626bf061d64c62ddf1

build:
  number: ${{ build_number }}

outputs:
  - package:
      name: libgz-sim-yarp-plugins
    build:
      script:
        - if: unix
          then:
            - build_cxx.sh
        - if: win
          then:
            - bld_cxx.bat
      string: ${{ GZ_DISTRO_VARIANT }}h${{ hash }}_${{ build_number }}
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ stdlib("c") }}
        - ${{ compiler('cxx') }}
        - cmake
        - pkg-config
        - ninja
        - multisheller
      host:
        - if: linux
          then:
            - xorg-libxfixes
            - libgl-devel
        - libyarp
        - libabseil
        - libprotobuf
        - if: GZ_DISTRO_VARIANT == "harmonic" or GZ_DISTRO_VARIANT == "ionic"
          then:
            - qt-main
          else:
            - qt6-main
        - if: GZ_DISTRO_VARIANT == "ionic" or GZ_DISTRO_VARIANT == "jetty"
          then:
            - spdlog
        # To avoid the need to manually build a matrix of version to compile in
        # conda_build_config.yaml, we depend on the meta-package gz-<distro>,
        # that will then constrain the version of all the dependent packages to the
        # correct version, that will then be exported as run dependencies via run_exports
        - gz-${{ GZ_DISTRO_VARIANT }}
        - libgz-math
        - libgz-plugin
        - libgz-msgs
        - libgz-transport
        - libgz-rendering
        - libgz-common
        - libsdformat
        - libgz-sim
        - gtest
      ignore_run_exports:
        by_name:
          - gtest
        from_package:
          - gtest
      run_exports:
        # See https://github.com/robotology/gz-sim-yarp-plugins/pull/237
        - ${{ pin_subpackage(cxx_name, upper_bound='x.x') }}
    tests:
      - package_contents:
          lib:
            - gz-sim-yarp-commons
            - gz-sim-yarp-basestate-system
            - gz-sim-yarp-camera-system
            - gz-sim-yarp-clock-system
            - gz-sim-yarp-controlboard-system
            - gz-sim-yarp-forcetorque-system
            - gz-sim-yarp-imu-system
            - gz-sim-yarp-laser-system
            - gz-sim-yarp-robotinterface-system
      # Test disabled for https://github.com/conda-forge/gz-sim-feedstock/issues/109
      # - script:
      #    - cmake-package-check gz-sim-yarp-plugins --targets gz-sim-yarp-plugins::gz-sim-yarp-device-registry gz-sim-yarp-plugins::gz-sim-yarp-commons
      #  requirements:
      #    run:
      #      - cmake-package-check
      #      - ${{ compiler('c') }}
      #      - ${{ compiler('cxx') }}

  - package:
      name: gz-sim-yarp-plugins
    build:
      # This ensure that we also have distro-specific variants for the gz-sim-yarp-plugins metapackage
      string: ${{ GZ_DISTRO_VARIANT }}h${{ hash }}_${{ build_number }}
    requirements:
      run:
        - ${{ pin_subpackage(cxx_name, exact=True) }}
    tests:
      - script:
          - echo "Metapackage, no test needed"

about:
  homepage: https://github.com/robotology/gz-sim-yarp-plugins
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'YARP plugins for Modern Gazebo (gz-sim).'

extra:
  feedstock-name: gz-sim-yarp-plugins
  recipe-maintainers:
    - Nicogene
    - xela-95
    - traversaro
